### ISSUE TITLE
Exception when sending an "action" using rpc callback

### ISSUE THREAD

**Issue by chaichairiko** [CESNET/libyang-python#10]
Hi,
While this is an issue that came up using sysrepo-python, this exception came from libyang-python:
`<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:5f367e03-50ef-4c28-a8b0-48dd54b4...or-path><nc:error-message xml:lang="en">'SNode' object is not iterable</nc:error-message></nc:rpc-error></nc:rpc-reply>`

When digging into the debugging this issue, I found it came from data.py:651 - 
`for s in schema_parent`

In our case, schema parent is an SNode already, so my initial thought was checking whether schema_parent was a list and if not, convert it into one. That fix does help, but its naive and I may be missing something.

Here is the relevant code that we are using for the application:
```
import signal
import sys
import sysrepo


def action_cb(rpc_input, event, private_data):
    print(str(rpc_input)+','+str( event)+','+str(private_data))
    print()
    print("========================")
    print("RPC call: %s" % rpc_input)
    return({'change_state':{'success':'we did it'}})

def module_change_cb(event, req_id, config, changes, private_data):
    print()
    print("========================")
    print("Module changed event: %s (request ID %s)" % (event, req_id))
    print("config = %s" % config)
    print("----- changes -----")
    for c in changes:
        print(repr(c))
    print("----- end of changes -----")
    print()


# ------------------------------------------------------------------------------
def main():
    with sysrepo.SysrepoConnection() as conn:
        with conn.start_session() as sess:
            print('starting')
            sess.subscribe_module_change("loadbalancer", None, module_change_cb)
            sess.subscribe_rpc_call("/loadbalancer:loadbalancer/nodes/change_state", action_cb)
            print('working')
            signal.sigwait({signal.SIGINT, signal.SIGTERM})



# ------------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(main())
```

The part of the yang module which is relevant:
```
        action change_state {
          input {
		    leaf desired_state {
              type desired_state;
		    }
          }
	      output {
		    leaf success {
			  type string;
		    }
	      }
        }
```

The XML sent:
```
<action xmlns="urn:ietf:params:xml:ns:yang:1">
                        <loadbalancer xmlns="insidepacket:loadbalancer">
                            <nodes>
                                <ip>10.0.0.20</ip>
                                <change_state>
                                    <desired_state>inactive</desired_state>
                                </change_state>
                            </nodes>
                        </loadbalancer>
                    </action>
```
(`ip` is the key in a list called `nodes`)

Regards,
Chai

**Comment by chaichairiko** [comment]
After more digging, I found the issue (something that is probably something you would find straight forward) - there is no "SAction". While SRpc has a __iter__ function, SNode does not. So as expected, the fix I tried is naive. I'll try and see what is needed to implement SAction

**Comment by rjarry** [comment]
Hi @chaichairiko,

yes, you identified the source of the problem. These bindings do not support schema action nodes yet. I guess the patch should be fairly easy since `rpc` and `action` are sharing a common structure `struct lys_node_rpc_action`.

Don't hesitate to ask if you need some help.

**Comment by chaichairiko** [comment]
Hi,
My first thought was copying the "SRpc" class and created "SAction" and also adding LYS_ACTION to a few places it was needed. While this solution worked and is finding "SAction", when trying to create "RpcOutput" (I saw no reason to change it) this for loop isn't working as expected:
```
        for s in schema_parent:
            if s.name() != name:
                continue
            mod = s.module()
            if prefix is not None and mod.name() != prefix:
                continue
            snode = s
            module = mod
            break
        schema_cache[cache_key] = (snode, module)
        return snode, module
```
`s` in my case is the leaf inside the action output, and `name` is the name of the action, so they will never be the same. As such this function return `None`.

Outside this function, in `_to_dnode` I finally get to the `warning` log in line 697.
Ultimately, nothing is returned since there is no node to merge.

I will run your RPC example to understand where the differences are
 
BTW, thank you for the implementations of both sysrepo-python and libyang-python. Its incredibly easier to debug and understand the "low level" implementations.

**Comment by rjarry** [comment]
I guess the more direct approach would be something like this:

```patch
diff --git a/libyang/data.py b/libyang/data.py
index 9a6d5b98a48c..c780258eb615 100644
--- a/libyang/data.py
+++ b/libyang/data.py
@@ -476,6 +476,7 @@ class DContainer(DNode):
 
 # -------------------------------------------------------------------------------------
 @DNode.register(SNode.RPC)
+@DNode.register(SNode.ACTION)
 class DRpc(DContainer):
     pass
 
diff --git a/libyang/schema.py b/libyang/schema.py
index a8cde8fa436a..e1bc5bff46a0 100644
--- a/libyang/schema.py
+++ b/libyang/schema.py
@@ -724,6 +724,7 @@ class SNode:
     LEAFLIST = lib.LYS_LEAFLIST
     LIST = lib.LYS_LIST
     RPC = lib.LYS_RPC
+    ACTION = lib.LYS_ACTION
     INPUT = lib.LYS_INPUT
     OUTPUT = lib.LYS_OUTPUT
     KEYWORDS = {
@@ -732,6 +733,7 @@ class SNode:
         LEAFLIST: "leaf-list",
         LIST: "list",
         RPC: "rpc",
+        ACTION: "action",
         INPUT: "input",
         OUTPUT: "output",
     }
@@ -1014,6 +1016,7 @@ class SRpcInOut(SNode):
 
 # -------------------------------------------------------------------------------------
 @SNode.register(SNode.RPC)
+@SNode.register(SNode.ACTION)
 class SRpc(SNode):
     def input(self) -> Optional[SRpcInOut]:
         try:
```

However, I did not test anything. If you can wait a bit, I'll implement a proper fix along with unit tests sometime before the end of the week.

**Comment by chaichairiko** [comment]
Hi, I've tested your solution, and while it is much cleaner - the result is the same -> getting a response with "ok" (as i it was an RPC call).
After doing some more testing (including the provided example for an rpc subscription in sysrepo-python), I have some questions that my shed light (at least for me). I know I am mixing up the issue I've opened in sysrepo-python, but since we both understand the issue I will continue this thread unless you prefer otherwise (I am not sure where the issue is after this fix).

In the function rpc_callback, there is a call to the function:
```
            dnode.merge_data_dict(
                output_dict, rpcreply=True, strict=subscription.strict, validate=False
            )
```
If I understand correctly, this `dnode` holds the data that will return, but, as I have written before 
> 
> ```
>         for s in schema_parent:
>             if s.name() != name:
>                 continue
>             mod = s.module()
>             if prefix is not None and mod.name() != prefix:
>                 continue
>             snode = s
>             module = mod
>             break
>         schema_cache[cache_key] = (snode, module)
>         return snode, module
> ```
> 
> `s` in my case is the leaf inside the action output, and `name` is the name of the action, so they will never be the same. As such this function return `None`.
> 
> Outside this function, in `_to_dnode` I finally get to the `warning` log in line 697.
> Ultimately, nothing is returned since there is no node to merge.

Nothing is returned, so dnode is not merged with the output. Again, this happens in RPC as well

**Comment by rjarry** [comment]
This patch is only part of the solution. Additional code will be required in sysrepo-python as well.

**Comment by rjarry** [comment]
Sorry for my laconic answer ;) I'll provide detailed explanations when I have a proper fix.

**Comment by chaichairiko** [comment]
Sure (:
I just wanted to point out that there might be an issue with the RPC as well

**Comment by rjarry** [comment]
Hi @chaichairiko libyang part should be OK now. But for complete action support, I need to fix stuff in sysrepo as well. I'll try to do that this week.
