### ISSUE TITLE
insert_attr support in libyang Python bindings

### ISSUE THREAD

**Issue by avazquezrd** [CESNET/libyang-python#42]
I am trying to use a function defined in libyang to insert an attribute into a data node ([`insert_attr()`](https://netopeer.liberouter.org/doc/libyang/libyang1/html/classlibyang_1_1_data___node.html#a248060ef232bf89e1376fb5b4fd3a732)). In particular, I need to insert the attribute `nc:operation=replace` (where `nc` represents namespace `urn:ietf:params:xml:ns:netconf:base:1.0`).

I have managed to do this with the old sysrepo/libyang bindings for 1.x versions as specified below, but have not found a way to do it with these bindings.

```python
module = context.get_module("ietf-netconf")
node.insert_attr(module, "operation", "replace")
```

I need this for cases where the _global_ operation specified in `edit_batch` is a `merge` (for example, a list of `/ietf-interfaces:interfaces`), but a particular node (each of the leafs within the list) needs a `replace`.

So, is there any way to do this with `libyang.DNode` class or some alternative?

**Comment by rjarry** [comment]
Hi there, data nodes attributes are not implemented in the python bindings yet. I assume you are referring to the old swig based bindings which are now deprecated.

I think it would be fairly easy to implement. Would you like to make a contribution?

**Comment by avazquezrd** [comment]
Yes, I am referring to the SWIG based bindings. A colleague is working on it, as soon as we do some tests and confirm that it works we will open a pull request. Thank you!

**Comment by avazquezrd** [comment]
@cristina-defran has added some changes that fix this. #43 should be ready to be merged.
