### ISSUE TITLE
Create empty root node

### ISSUE THREAD

**Issue by singularsyntax** [CESNET/libyang-python#49]
Hello,

Considering the following YANG data file and a `libyang` context with the required modules loaded, I can call `context.parse_data_file(...)` and produce a top-level `DNode` with the given data sub-trees:

    {
        "openconfig-system:system": {
            // stuff
        },
        "openconfig-interfaces:interfaces": {
            // stuff
        }
    }

However, what I want to do is the reverse - produce these data sub-trees from code as Python `dict` objects, transform them to `DContainer` instances via a call to `Module.parse_data_dict(...)`, and add them to a top-level `Dnode` instance. I know that this is possible structurally as it would be what `context.parse_data_file(...)` does under the hood.

However, I can't find a way to create an empty top-level `DNode` and add the sub-trees to it via the `libyang-python` API. Is it possible?

**Comment by singularsyntax** [comment]
If I do the following on a file `oc-conf.json` with data like above (except expanded, with many child nodes):

    file = open('oc-conf.json')
    top = yang_context.parse_data_file(file, 'json', no_state=True, strict=True, validate_present=True)
    file.close()
    
    print('### FILE ###')
    
    pprint(top)
    for sib in top.siblings():
        print(sib)

I see output like this:

    ### FILE ###
    <libyang.data.DContainer: interfaces>
    interfaces
    system

If I do something like this:

    print('### DICT ###')
    
    yang_data = {
        "openconfig-system:system": { ... },
        "openconfig-interfaces:interfaces": { ... }
    }
    
    for root_node in yang_data.keys():
        dnode = yang_context.create_data_path('/' + root_node)
        dnode.merge_data_dict(yang_data[root_node], no_state=True, strict=True, validate_present=True)
    
    pprint(dnode)
    for sib in dnode.siblings():
        print(sib)

Then the output is:

    ### DICT ###
    <libyang.data.DContainer: system>
    system
    <libyang.data.DContainer: interfaces>
    interfaces

Okay, so maybe I can concatenate the siblings somehow so that the resulting `DContainer` instance looks like the file parse example. I tried something like:

    top = None

    for root_node in yang_data.keys():
        dnode = yang_context.create_data_path('/' + root_node)
        dnode.merge_data_dict(yang_data[root_node], no_state=True, strict=True, validate_present=True)
    
    if top is None:
        top = dnode
    else:
        ret = lib.lyd_insert_sibling(top.cdata, dnode.cdata, ffi.NULL)
        if ret != lib.LY_SUCCESS:
            raise Exception('sibling insert failed')

This doesn't work, because the library doesn't define `lyd_insert_sibling` or its related functions. I've also tried various ways of calling the `DNode.merge_XXX` methods, without success. I just can't get it to create a combined `DNode` instance like the file parse does.

**Comment by singularsyntax** [comment]
I ended up solving this by generating configuration as a Python `dict`, converting to JSON, then parsing with `context.parse_data_mem(...)`.  From there, I can continue with whatever `DNode` manipulations are needed. The JSON conversion step is necessary because only `context` understands and is able to parse NETCONF `nc:operation` attributes.

I think it would be useful to have a context-level `parse_data_dict()` method that understands and can parse multiple namespace'd siblings like `context.parse_data_mem(...)` does to avoid the intermediate conversion step to JSON, but that is beyond my current level of expertise with the `libyang-python` code base and the time I have available right now to invest in such an effort.

**Comment by slinkish** [comment]
I am interested in continuing this conversation and finding a viable solution to this issue.
Here is some additional debugging that I came up with.
You will have to forgive my ignornance of python FFI and this may be all very simple to explain.

Added debugs to DNode.merge():
```
    def merge(
        self,
        source: "DNode",
        with_siblings: bool = False,
        defaults: bool = False,
        destruct: bool = False,
        with_flags: bool = False,
    ) -> None:
        flags = merge_flags(defaults=defaults, destruct=destruct, with_flags=with_flags)
        node_p = ffi.new("struct lyd_node **")
        node_p[0] = self.cdata
        print(f'debug self: {self.cdata}')
        print(f'debug target - pre call: {node_p[0]}')
        if with_siblings:
            ret = lib.lyd_merge_siblings(node_p, source.cdata, flags)
        else:
            ret = lib.lyd_merge_tree(node_p, source.cdata, flags)

        if ret != lib.LY_SUCCESS:
            raise self.context.error("merge failed")

        print(f'debug target - post call: {node_p[0]}')
        return node_p
```
Result:
```
>>> from libyang import Context, DContainer
>>> from config.iosxr.primitives import lldp_base, aaa_base
>>>
>>> ctx = Context('/yang/cisco/791/')
>>> ctx.load_module('Cisco-IOS-XR-ethernet-lldp-cfg').feature_enable_all()
>>> ctx.load_module('Cisco-IOS-XR-aaa-lib-cfg').feature_enable_all()
>>>
>>> lldp_mod = ctx.get_module('Cisco-IOS-XR-ethernet-lldp-cfg')
>>> config = lldp_mod.parse_data_dict(lldp_base(), strict=True, validate_present=True)
>>>
>>> aaa_mod = ctx.get_module('Cisco-IOS-XR-aaa-lib-cfg')
>>> aaa_config = aaa_mod.parse_data_dict(aaa_base(), strict=True, validate_present=True)
>>>
>>> alt_cdata = config.merge(aaa_config, with_siblings=True)[0]
debug self: <cdata 'struct lyd_node *' 0x7f2a580f8350>
debug target - pre call: <cdata 'struct lyd_node *' 0x7f2a580f8350>
debug target - post call: <cdata 'struct lyd_node *' 0x7f2a580a3820>
>>> alt_config = DContainer(ctx, alt_cdata)
```
It appears the call the C function is creating a new object with a new address in place of variable `node_p` leaving `self.cdata` unmodified.
I have verified that the new object contains the expected merged tree.

Is this a viable patch to the problem?:
```
    def merge(
        self,
        source: "DNode",
        with_siblings: bool = False,
        defaults: bool = False,
        destruct: bool = False,
        with_flags: bool = False,
    ) -> None:
        flags = merge_flags(defaults=defaults, destruct=destruct, with_flags=with_flags)
        node_p = ffi.new("struct lyd_node **")
        node_p[0] = self.cdata
        if with_siblings:
            ret = lib.lyd_merge_siblings(node_p, source.cdata, flags)
        else:
            ret = lib.lyd_merge_tree(node_p, source.cdata, flags)

        if ret != lib.LY_SUCCESS:
            raise self.context.error("merge failed")

        self.cdata = node_p[0]
```
It certainly works based my hack testing hah. I was also slightly concerned by the C documentation that says:
```
Merge may not be complete until validation called on the resulting data tree (data from more cases may be present, default and non-default values).
```
I played around with a couple of the validation methods in the python context with no observable impact to the merge result.
