### ISSUE TITLE
Tree traversal questions

### ISSUE THREAD

**Issue by li-pingmao** [CESNET/libyang-python#51]
Would like tree traversal functions,  for example, libyang2 lysc_tree_dfs_full (),   could it be added or how could we add them?  thanks.

**Comment by rjarry** [comment]
I would prefer a `SNode.walk()` and `DNode.walk()` kind of API. It would be more consistent with the Python ecosystem.

Behind the scenes, these functions could call `lysc_tree_dfs_full` or manually walk through the tree. For data nodes, there only are C macros so they cannot be reused in Python. I assume that an iterator that accesses `struct lysc_node` and `struct lyd_node` fields to do a DFS would be more suitable.

**Comment by rjarry** [comment]
Actually, there already is `DNode.iter_tree()`.

https://github.com/CESNET/libyang-python/blob/v2.4.0/libyang/data.py#L556-L571

For schema nodes, it should not be hard to reimplement a similar function.

**Comment by li-pingmao** [comment]
Thanks!

**Comment by li-pingmao** [comment]
Will a similar function iter_tree() be added to schema nodes?

**Comment by rjarry** [comment]
I just added it 🙂

**Comment by li-pingmao** [comment]
Awesome,  that is so quick.

Will a new version with this available soon in PyPI?

**Comment by rjarry** [comment]
There you go: https://pypi.org/project/libyang/2.5.0/

**Comment by li-pingmao** [comment]
Thanks a lot
