### ISSUE TITLE
Libyang python bindings for windows

### ISSUE THREAD

**Issue by prasadpkorhale** [CESNET/libyang-python#55]
A project that I am working on needs to access the [libyang](https://github.com/CESNET/libyang) C library via Python on Windows. It seems that libyang library has been ported to run on windows. 

So, I was curious if there is any effort that you are aware of to build the python bindings for windows using the already defined CFFI interfaces? I assume CFFI interfaces won't change themselves but the orchestration to build on windows will need to be setup.

Happy to contribute if needed. But just wanted to check before I started looking into it.

**Comment by rjarry** [comment]
Hi there,

I will not have time to maintain any windows compatibility. However if you want to add some CI configuration [here](https://github.com/CESNET/libyang-python/blob/master/.github/workflows/ci.yml) we can discuss on specifics.

Thanks!

**Comment by samuel-gauthier** [comment]
Not planned at the moment, please reopen if needed.
