### ISSUE TITLE
libyang python 2.7.0 not able to build with CFFI bindings

### ISSUE THREAD

**Issue by TeSwen** [CESNET/libyang-python#64]
During a dockerfile build based on Ubuntu 23.04 seeing this compilation error:

#14 [base 11/11] RUN   ./virt_env/bin/pip install sysrepo
#14 sha256:00fc43cda2611ee0fe616c946cf1bc1c162a6f2743f5ffc59c4b3cd7041178d6
#14 5.245 Looking in indexes: https://nexus.engapps.<path deleted>
#14 8.022 Collecting sysrepo
#14 9.250   Downloading https://nexus.engapps.<path deleted>/sysrepo/1.4.0/sysrepo-1.4.0.tar.gz (33 kB)
#14 9.290   Installing build dependencies: started
#14 20.78   Installing build dependencies: finished with status 'done'
#14 20.78   Getting requirements to build wheel: started
#14 20.94   Getting requirements to build wheel: finished with status 'done'
#14 20.95   Installing backend dependencies: started
#14 24.12   Installing backend dependencies: finished with status 'done'
#14 24.12   Preparing metadata (pyproject.toml): started
#14 24.46   Preparing metadata (pyproject.toml): finished with status 'done'
#14 25.92 Collecting libyang>=2.1
#14 27.06   Downloading https://nexus.engapps.<path deleted>/libyang/2.7.0/libyang-2.7.0.tar.gz (55 kB)
#14 27.08      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.4/55.4 kB 6.0 MB/s eta 0:00:00
#14 27.16   Installing build dependencies: started
#14 37.45   Installing build dependencies: finished with status 'done'
#14 37.45   Getting requirements to build wheel: started
#14 37.66   Getting requirements to build wheel: finished with status 'done'
#14 37.66   Installing backend dependencies: started
#14 40.88   Installing backend dependencies: finished with status 'done'
#14 40.88   Preparing metadata (pyproject.toml): started
#14 41.52   Preparing metadata (pyproject.toml): finished with status 'done'
#14 43.50 Collecting cffi
#14 44.65   Using cached https://nexus.engapps.<path deleted>/packages/cffi/1.15.1/cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
#14 46.01 Collecting pycparser
#14 47.16   Using cached https://nexus.engapps.<path deleted>/packages/pycparser/2.21/pycparser-2.21-py2.py3-none-any.whl (118 kB)
#14 47.16 Building wheels for collected packages: sysrepo, libyang
#14 47.16   Building wheel for sysrepo (pyproject.toml): started
#14 49.10   Building wheel for sysrepo (pyproject.toml): finished with status 'done'
#14 49.10   Created wheel for sysrepo: filename=sysrepo-1.4.0-cp311-cp311-linux_x86_64.whl size=102757 sha256=d44b6e9c8572990c9e85ad9093729d9441d667330548a5a575bac89f7dfa1af1
#14 49.10   Stored in directory: /root/.cache/pip/wheels/46/86/78/9bc072c08658d4b4f9805a230699fe6fb555e5832445bf3aae
#14 49.10   Building wheel for libyang (pyproject.toml): started
#14 51.51   Building wheel for libyang (pyproject.toml): finished with status 'error'
#14 51.52   error: subprocess-exited-with-error
#14 51.52
#14 51.52   × Building wheel for libyang (pyproject.toml) did not run successfully.
#14 51.52   │ exit code: 1
#14 51.52   ╰─> [39 lines of output]
#14 51.52       running bdist_wheel
#14 51.52       running build
#14 51.52       running build_py
#14 51.52       creating build
#14 51.52       creating build/lib.linux-x86_64-cpython-311
#14 51.52       creating build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/__init__.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/context.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/data.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/diff.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/keyed_list.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/log.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/schema.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/util.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/xpath.py -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       running egg_info
#14 51.52       writing libyang.egg-info/PKG-INFO
#14 51.52       writing dependency_links to libyang.egg-info/dependency_links.txt
#14 51.52       writing requirements to libyang.egg-info/requires.txt
#14 51.52       writing top-level names to libyang.egg-info/top_level.txt
#14 51.52       reading manifest file 'libyang.egg-info/SOURCES.txt'
#14 51.52       reading manifest template 'MANIFEST.in'
#14 51.52       adding license file 'LICENSE'
#14 51.52       writing manifest file 'libyang.egg-info/SOURCES.txt'
#14 51.52       copying libyang/VERSION -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       copying libyang/py.typed -> build/lib.linux-x86_64-cpython-311/libyang
#14 51.52       running build_ext
#14 51.52       generating cffi module 'build/temp.linux-x86_64-cpython-311/_libyang.c'
#14 51.52       creating build/temp.linux-x86_64-cpython-311
#14 51.52       building '_libyang' extension
#14 51.52       creating build/temp.linux-x86_64-cpython-311/build
#14 51.52       creating build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311
#14 51.52       x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/opt/dev/virt_env/include -I/usr/include/python3.11 -c build/temp.linux-x86_64-cpython-311/_libyang.c -o build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311/_libyang.o -Werror -std=c99
#14 51.52       build/temp.linux-x86_64-cpython-311/_libyang.c: In function ‘_cffi_checkfld_struct_lyd_node_inner’:
#14 51.52       build/temp.linux-x86_64-cpython-311/_libyang.c:8143:32: error: initialization of ‘struct hash_table **’ from incompatible pointer type ‘struct ly_ht **’ [-Werror=incompatible-pointer-types]
#14 51.52        8143 |   { struct hash_table * *tmp = &p->children_ht; (void)tmp; }
#14 51.52             |                                ^
#14 51.52       cc1: all warnings being treated as errors
#14 51.52       error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
#14 51.52       [end of output]
#14 51.52
#14 51.52   note: This error originates from a subprocess, and is likely not a problem with pip.
#14 51.52   ERROR: Failed building wheel for libyang
#14 51.52 Successfully built sysrepo
#14 51.52 Failed to build libyang
#14 51.52 ERROR: Could not build wheels for libyang, which is required to install pyproject.toml-based projects
#14 ERROR: executor failed running [/bin/sh -c python3 -m venv ./virt_env &&     . ./virt_env/bin/activate &&     ./virt_env/bin/pip install sysrepo]: exit code: 1

**Comment by sjd-xlnx** [comment]
I have same issue when trying to upgrade to 2.7.0.
pip install --upgrade libyang

```
Building wheels for collected packages: libyang
  Building wheel for libyang (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for libyang (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/__init__.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/keyed_list.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/log.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/schema.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/xpath.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/data.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/diff.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/util.py -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/context.py -> build/lib.linux-x86_64-cpython-37/libyang
      running egg_info
      writing libyang.egg-info/PKG-INFO
      writing dependency_links to libyang.egg-info/dependency_links.txt
      writing requirements to libyang.egg-info/requires.txt
      writing top-level names to libyang.egg-info/top_level.txt
      reading manifest file 'libyang.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'libyang.egg-info/SOURCES.txt'
      copying libyang/VERSION -> build/lib.linux-x86_64-cpython-37/libyang
      copying libyang/py.typed -> build/lib.linux-x86_64-cpython-37/libyang
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-cpython-37/_libyang.c'
      creating build/temp.linux-x86_64-cpython-37
      building '_libyang' extension
      creating build/temp.linux-x86_64-cpython-37/build
      creating build/temp.linux-x86_64-cpython-37/build/temp.linux-x86_64-cpython-37
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/stevend/.local/include -I/tools/cpkg/.packages/x86_64/RHEL7.2/python/3.7.1/include/python3.7m -c build/temp.linux-x86_64-cpython-37/_libyang.c -o build/temp.linux-x86_64-cpython-37/build/temp.linux-x86_64-cpython-37/_libyang.o -Werror -std=c99
      build/temp.linux-x86_64-cpython-37/_libyang.c: In function ‘_cffi_checkfld_struct_lyd_node_inner’:
      build/temp.linux-x86_64-cpython-37/_libyang.c:8143:32: error: initialization of ‘struct hash_table **’ from incompatible pointer type ‘struct ly_ht **’ [-Werror=incompatible-pointer-types]
       8143 |   { struct hash_table * *tmp = &p->children_ht; (void)tmp; }
            |                                ^
      cc1: all warnings being treated as errors
      error: command '/tools/gensys/riviera/2022.04-lin64/gcc_Linux64/bin/gcc' failed with exit code 1
      [end of output]
```

It's falling over with `{ struct hash_table * *tmp = &p->children_ht; (void)tmp; }` which is a warning, but warnings are treated as errors when building the wheel. Is there a way to disable the warning? I tried adding `LIBYANG_EXTRA_FLAGS -Wno-error` but this didn't work.

**Comment by rjarry** [comment]
Fixed in commit https://github.com/CESNET/libyang-python/commit/d5957da13ec67cf2996ba86d66412392156c55d5

The fix should be available in 2.7.1: https://pypi.org/project/libyang/2.7.1/

**Comment by TeSwen** [comment]
If it still matters I was able to get around this by changing the build.py script to ignore the warning.   
1) Clone the repository: git clone https://github.com/CESNET/libyang-python.git
2) Modify build.py: sed -i "s/\"-Werror\"/\"-Werror\", \"-Wno-error=incompatible-pointer-types\" /g" ./libyang-python/cffi/build.py
3) cd libyang-python
4) python3 setup.py install

**Comment by rjarry** [comment]
Oh you could have done that without such hassle :)

```
LIBYANG_EXTRA_CFLAGS=-Wno-error=incompatible-pointer-types pip install -U libyang
```
